(lang dune 3.23)

(name camels)

(generate_opam_files true)

(source
 (github mrdijk/camels))

(authors "Maurits Dijk mauritsdijk@gmail.com")

(maintainers "Maurits Dijk mauritsdijk@gmail.com")

(license GLP-3.0)

(documentation https://github.com/mrdijk/camels)

(package
 (name camels)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
